### ISSUE TITLE
Первичный код

### ISSUE THREAD

**Issue by TrustyWork** [TrustyWork/PRP-RestApp#1]
Должно включать в себя 
- веб сокеты (через Socket.io)
- экспресс
- паспорт
- монгус (юзеры - [схема Лены](https://i.gyazo.com/6bab0071ba67283342830f36e14c543c.png))
- nconf для конфигураций
- гео локацию (вариант Ромы)

**Comment by vvroman** [comment]
Вопрос по схеме: есть такой плагин для Монгуса: passport-local-mongoose которьій добавляет в схему методьі  и поля для локальной аутентификации (User/password). Может попробовать использовать его в нашей схеме. Все его поля кроме "name" пусть будут в UserSchema.auth { local : { __ЗДЕСЬ__}}.  

ОК?

**Comment by vvroman** [comment]
К сожалению модуль passport-local-mongoose не работает с вложенньіми схемами:

из исходников:
__if (!user.get(options.usernameField))__ {
      return cb(new errors.MissingUsernameError(options.errorMessages.MissingUsernameError));
    }
Єто раб. только без вложений.

С Nested Schema нужно делать так :+1: __user.auth.local.get('username')__ 
Так что к сожалению либо данньіе локальной аутентификации вьіносим наверх схмьі - либо пишем аутентификацию сами. (я за вьінос наверх).

Решение???

**Comment by TrustyWork** [comment]
Возможный вариант, предлагаю обсудить это в субботу.

**Comment by TrustyWork** [comment]
Залил версию Ромы, сегодня разберем недочеты.
